/localization_lifecycle_manager:
  ros__parameters:
    autostart: True
    use_sim_time: True
    bond_timeout: 8.0
    node_names: ['map_server', 'amcl']
    attempt_respawn_reconnection: True
    bond_respawn_max_duration: 15.0
    service_introspection_mode: "disabled"
    allow_parameter_qos_overrides: True

/amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    base_frame_id: base_footprint
    do_beamskip: False
    global_frame_id: map
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 5.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 1000
    min_particles: 300
    odom_frame_id: odom
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: True
    transform_tolerance: 0.5
    service_introspection_mode: "disabled"
    update_min_a: 0.15
    update_min_d: 0.15
    z_hit: 0.5
    z_rand: 0.5
    scan_topic: /scan
    map_topic: /map
    always_reset_initial_pose: False
    first_map_only: False
    bond_heartbeat_period: 0.5
    allow_parameter_qos_overrides: True
    set_initial_pose: True
    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 0.0
      z: 0.0
